name: Eleventy Build

on:
  push:
    branches:
      - source
      - main
  schedule:
    # everyday at 8 PM UTC
    - cron: '0 20 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn build
        env:
          GA_API_ENDPOINT: ${{ secrets.GA_API_ENDPOINT }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
          cname: manishm.com.np
